### ISSUE TITLE
Eingabemaske und Editview in Chrome, Notation Editor: Close-Funktion

### ISSUE THREAD

**Issue by elena1113** [Score4LMS/SingleChoiceScore4LMS#3]
Task Descriptions und Task Content: ohne Noten und mit Text -> es wird leerer Noteneditor (Pausen) in Resultview, also nach dem Speichern, angezeigt
Task Descriptions und Task Content: Löschen alle Noten -> wenn man die Noten löscht, werden die Pausen dargestellt. -> es wird leerer Noteneditor (Pausen) in Resultview angezeigt

**Comment by mnowakow** [comment]
Änderungen werden im Dialog vorgenommen. Prüfung, ob Notation über H5P-Konfigurationen ein-/ausgeschaltet werden kann

**Comment by mnowakow** [comment]
@elena1113 Könntest du bitte die komplette, geänderte semantics.json anhängen?

**Comment by mnowakow** [comment]
Das Notation Widget hat jetzt ein optionales Event, sodass es jetzt mit Listen in H5P funktioniert. Notationen können nun aus den Questions gelöscht werden. Notation Widget wurde auf v 1.1.12 hochgesetzt

**Comment by elena1113** [comment]
commit ca9eed932ff35f673d259e9d0caff0d049b58d46
fixed
